version: '3.7'
services:

  postgres:
    image: postgres:12-alpine
    environment:
      PG_USER: postgres
      PG_PASSWORD: pgpass
      PG_HOST: postgres
      PG_DATABASE: postgres
      PG_PORT: 5432
      PG_SSLMODE: false

    ports:
      - "5432:5432"

  migrations:
    image: migrate/migrate
    volumes:
      - migrations/projects:/migrations
    command: -path=/migrations/ -database postgres://projects-admin:pgpass@postgres:5432/projects?sslmode=disable up

